-
  name: install packages from Centos8
  hosts: test1
  become: yes
  tasks:
    - name: install packages
      dnf:
        name: "{{ packages_1 }}"
        state: latest
      vars:
        packages_1:
        - epel-release
        - python3.9
        - conntrack-tools
        - dnf-utils
        - ca-certificates
        - device-mapper-persistent-data
        - lvm2

    - name: update Centos8
      dnf:
        name: '*'
        state: latest

    - name: update pip and setuptools
      pip:
        name:
          - pip
          - setuptools
        extra_args: --upgrade
        executable: pip3

    - name: Add repository Docker
      shell: yum-config-manager  --add-repo https://download.docker.com/linux/centos/docker-ce.repo

    - name: Install Docker
      dnf:
        name: "{{ packages_2 }}"
        state: latest
      vars:
        packages_2:
          - docker-ce
          - docker-ce-cli
          - containerd.io

    - name: Start service docker
      service:
        name: docker
        enabled: yes
        state: started

    - name: Enabled service containerd
      service:
       name: containerd
       enabled: yes
       state: started

    - name: Add user to Docker group
      user:
        name: enigma
        group: docker
        append: yes

    - name: Add repository k8s
      yum_repository:
        name: Kubernetes
        description: k8s repo
        baseurl: https://packages.cloud.google.com/yum/repos/kubernetes-el7-x86_64
        gpgcheck: yes
        gpgkey: https://packages.cloud.google.com/yum/doc/yum-key.gpg https://packages.cloud.google.com/yum/doc/rpm-package-key.gpg
        exclude: kubelet kubeadm kubectl
        enabled: yes

    - name: Install Kubernetes
      shell:
        cmd: sudo yum install -y kubelet kubeadm kubectl --disableexcludes=Kubernetes

    - name: Start kubelet
      service:
        name: kubelet
        enabled: yes
        state: started

    - name: Letting iptables see bridged traffic
      shell: |
        sudo modprobe br_netfilter
        lsmod | grep br_netfilter

    - name: Letting iptables see bridged traffic
      shell:
        cmd: |
          cat <<EOF | sudo tee /etc/sysctl.d/k8s.conf
          net.bridge.bridge-nf-call-ip6tables = 1
          net.bridge.bridge-nf-call-iptables = 1
          EOF
          sudo sysctl --system


- name: Configure Master node
  hosts: Master
  become: yes
  tasks:
    - name:
